Lang.prototype.pack.it = {
  "token": {
    "CITY": "CITTÀ",
    "REGION": "REGIONE",
    "ABOUT": "INFO",
    "Search by city": "Ricerca per città",
    "Search by Region": "Ricerca per regione",
    "There are incomplete required fields. Please complete them.": "Alcuni campi non sono stati completati.",
    "No results found!": "Nessun risltato trovato!",
    "Please start a new search": "Si prega di eseguire una nuova ricerca.",
    "Close": "Chiudi",
    "SEARCH": "Cerca",
    "Name": "Nome",
    "State": "Stato",
    "Region": "Regione",
    "City": "Città",
    "Housing": "Alloggio",
    "Restaurants": "Ristoranti",
    "Maps": "Mappa",
    "Address": "Indirizzo",
    "Phone": "Telefono",
    "history": "Era l'anno 990 d.C., quando, durante il suo viaggio di ritorno da Roma alla sua sede episcopale, l’Arcivescovo Sigerico annotò le 79 “submansiones de Roma usque ad mare”, ossia le tappe che anno scandito il suo incedere verso la natale Canterbury. Questa antica Via che unisce Canterbury a Roma e ai porti della Puglia è stata riscoperta dai moderni viandanti, che si mettono in camino lungo un percorso splendido e sorprendente. Dal 2001 l’Associazione Europea delle Vie Francigene promuove lo sviluppo e la valorizzazione di un Itinerario che attraversando l’Europa ripercorre la storia di una parte importante del nostro continente. Mille anni di storia e più di duemila chilometri di tradizioni, natura e cultura attraverso Inghilterra, Francia, Svizzera e Italia si trovano al centri del progetto europeo. Una “Via di culture”, come la definì Jacques Le Goff, lungo la quale costruiamo l’Europa dei popoli.",
    "title": "La Via Francigena",
    "Leg": "Tappa",
  }
}